services:
  gpu:
    container_name: try_rye_gpu
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    image: try_rye_gpu
    shm_size: '28gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    tty: true

  cpu:
    container_name: try_rye
    build:
      context: .
      dockerfile: docker/Dockerfile.cpu
    image: try_rye_cpu
    shm_size: '16gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
        consistency: delegated
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    tty: true

volumes:
  venv:
