defaults:
  - model: lgb
  - _self_

data:
  train_path: "../data/input/train.csv"
  anime_path: "../data/input/anime.csv"
  test_path: "../data/input/test.csv"
  submission_path: "../data/input/sample_submission.csv"
  output_path: "../data/output/"

seed: 42
